config/routes.rb
Rails.application.routes.draw do
  get 'mat_stats/index'

  get 'mat_stats/registration'
  get 'mat_stats', to: 'mat_stats#forget'
  post 'new_user', to: 'mat_stats#newUser'
  post 'process_date', to: 'mat_stats#processDate'
  post 'enter', to: 'mat_stats#enter'
  get 'static_pages/index'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'

  post 'matstat', to: 'process#matstat'

  root 'static_pages#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<!doctype html>

<style>
	body
{
background: url(images/background.png) repeat;
padding:0; margin:0;
}
  #content{
    float:left;
  }

  #sidebar{
  float: right;
    padding: 16px;
  }
  .close{
    margin-left: 364px;
    margin-top: 4px;
    cursor: pointer;
  }
</style>

<html>

	<head>
	  <meta charset="utf8">
	</head>

  <body>

    <div id="content">
      <h1>Выбирите сервис</h1>
      <%= link_to "Математическая статистика",controller: "mat_stats", action: "index" %>
    </div>
      <div id="sidebar">
          <% if (!signed_in?) %>
          <%= form_for(:session, url: sessions_path) do |f| %>

            <p><%= f.label :email %>
              <%= f.text_field :email %></p>

            <p> <%= f.label :password %>
              <%= f.password_field :password %></p>

            <%= f.submit "Sign in" %>
        <% end %>


    <%= link_to "Регистрация",controller: "mat_stats", action: "registration" %>
    <%= link_to "Забыли пароль ?",controller: "mat_stats", action: "forget" %>
            <% else %>
        <%=sprintf("Привет,") %>
            <%=current_user.first_name%>
            <%= link_to "Выйти", controller: "sessions", action: "destroy" %>
        <%end %>

  </div>

  </body>
</html>